### ISSUE TITLE
Several minor issues with installing lbry

### ISSUE THREAD

**Issue by fcolecumberri** [lbryio/lbry-gentoo-overlay#7]
Hi, I am trying to install lbry in gentoo, but I get several issues with some packages:

# unqlite

Here I get an error about a base 8 number that is not base 8:
~~~
Traceback (most recent call last):
  File "ctypesgen/ctypesgen.py", line 136, in <module>
    descriptions=ctypesgencore.parser.parse(options.headers,options)
  File "/var/tmp/portage/dev-python/unqlite-0.2.0/work/unqlite-0.2.0/ctypesgen/ctypesgencore/parser/__init__.py", line 21, in parse
    parser.parse()
  File "/var/tmp/portage/dev-python/unqlite-0.2.0/work/unqlite-0.2.0/ctypesgen/ctypesgencore/parser/datacollectingparser.py", line 69, in parse
    ctypesparser.CtypesParser.parse(self, fname, None)
  File "/var/tmp/portage/dev-python/unqlite-0.2.0/work/unqlite-0.2.0/ctypesgen/ctypesgencore/parser/cparser.py", line 113, in parse
    self.preprocessor_parser.parse(filename)
  File "/var/tmp/portage/dev-python/unqlite-0.2.0/work/unqlite-0.2.0/ctypesgen/ctypesgencore/parser/preprocessor.py", line 200, in parse
    token = self.lexer.token()
  File "/var/tmp/portage/dev-python/unqlite-0.2.0/work/unqlite-0.2.0/ctypesgen/ctypesgencore/parser/preprocessor.py", line 51, in token
    result = lex.Lexer.token(self)
  File "/var/tmp/portage/dev-python/unqlite-0.2.0/work/unqlite-0.2.0/ctypesgen/ctypesgencore/parser/lex.py", line 297, in token
    newtok = func(tok)
  File "/var/tmp/portage/dev-python/unqlite-0.2.0/work/unqlite-0.2.0/ctypesgen/ctypesgencore/parser/pplexer.py", line 218, in t_ANY_int
    g1 = str(long(g1,8))
ValueError: invalid literal for long() with base 8: '08420217248550443400745280086994171'
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    cmdclass={'build_py': GenerateCtypesWrapper},
  File "/usr/lib64/python2.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 28, in run
    wrapper])
  File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'ctypesgen/ctypesgen.py', 'unqlite/src/unqlite.h', '-L', './', '-l', 'unqlite', '-o', '/var/tmp/portage/dev-python/unqlite-0.2.0/work/unqlite-0.2.0/unqlite/_unqlite.py']' returned non-zero exit status 1
~~~

the full log is here: 
[unqlite.log](https://github.com/lbryio/lbry-gentoo-overlay/files/3387827/unqlite.log)

# lybryum

When you use qt4 flag it pulls dev-python/PyQt4 which is no longer available since like 1 year ago. maybe you want to migrate to dev-python/PyQt5 or at least remove the flag and its dependency.

# seccure

You made seccure depends on several twisted modules, but since you may have installed dev-python/twisted (which is a package that provides all modules and conflicts with the separated modules) you may want to set the option to have the modules or the full package, I needed to uninstall the package and install the modules to work around this issue, but you may just use a syntax like:
~~~
( || ( $(python_gen_cond_dep 'dev-python/twisted[${PYTHON_USEDEP}]' python2_7 python3_{5,6})
$(python_gen_cond_dep 'dev-python/twisted-core[${PYTHON_USEDEP}]' python2_7)
~~~

I took  those lines from the dev-python/nose package ebuild file.

# lybryum (again)

do you really depends on `<=dev-libs/protobuf-3.0.0_beta2` ? I mean the .deb file you give in your main page doesn't depends on that and I have tons of software that depends on newer versions (at least 3.6)

# python

you use a lot python 2, but it is going to be deprecated on favour of python3 in 6 months

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. This repo is very outdated and not maintained. Is this something you'd be interested in fixing up / getting up to speed with our latest sdk? If not, I'll be archiving it.

**Comment by fcolecumberri** [comment]
oh it's a shame to hear that, but I think it is better, I have just installed the https://github.com/lbryio/lbry-desktop version and it was way easier than trying to fix this ebuilds yhe only thing is that it asumes that every linux user is a ubuntu/debian/mint/... user so it is needed to extract the generated .deb and copy it to /opt

thanks anyway

**Comment by mschilli87** [comment]
@fcolecumberri: Would you mind sharing how exactly you got this to work.
I'd love to revive this ebuild but didn't manage to build lbry from source on my Gentoo machine yet.
I didn't have much time to try though yet.

**Comment by fcolecumberri** [comment]
ok, the instructions are simple:

  1. git clone https://github.com/lbryio/lbry-desktop
  1. cd lbry-desktop
  1. yarn # this will download deps into the lbry-desktop directory 
  1. yarn build
  1. cd dist/electron/ # I can't remember if it was here, search for the .deb file
  1. extract the .deb content, you will see a opt, usr and debian directories
  1. check in the debian file that you have installed the software it asks
  1. sudo copy the opt content in /opt
  1. sudo copy the usr content in /usr
  1. (optional) create a symbolic link of /opt/LBRY to /usr/local/bin or create the file /usr/local/bin/LBRY  with the line `/opt/LBRY`

I think this should work on any non-debian linux, so maybe I will make a script next weekend since this process should be made each time you want to update.

**Comment by fcolecumberri** [comment]
I have finished my script, if a non-debian-based linux user want to install the current LBRY from git (or update, I have just updated using this script)

https://github.com/fcolecumberri/lbry_generic_linux_install

**Comment by whitslack** [comment]
@fcolecumberri: Since you have a script already, it wouldn't be that big a leap for you to go ahead and make a net-p2p/lbry-bin ebuild for Gentoo. Just install everything into ${D}/opt from the ebuild, and the package manager (e.g., Portage) will take care of placing everything into the live file system. The advantage is that all installed files would be registered with the package manager for ease of identification and completeness of uninstallation.

**Comment by fcolecumberri** [comment]
@whitslack I have never built an ebuild, but I want to learn how to build an ebuild, so I will take this opportunity to make my first, but that might be next weekend. I hope that script will at least be useful at the moment.

**Comment by whitslack** [comment]
@fcolecumberri: It's easy if you are already proficient in Bash scripting, especially if, as in this case, you're not actually building anything but are really just installing prebuilt files (thus the "-bin" suffix on the ebuild name). Perfect opportunity to learn! :)

**Comment by kauffj** [comment]
@fcolecumberri @mschilli87 (and @whitslack), if any of you would be interested in joining/forming a LBRY Hive centered around Gentoo I think it would be a great fit. And you get to join a club with a super secret handshake.

You can read more about how it works here: https://lbry.com/swarm
